from __future__ import annotations

from typing import Protocol

from embodied_skill_composer.core.models import (
    PerceptionReport,
    SensorObservation,
    SkillResult,
    SkillStep,
    TaskSpec,
    WorldState,
)


class SimulationAdapter(Protocol):
    def reset(self, seed: int | None = None) -> None: ...

    def get_world_state(self) -> WorldState: ...

    def move_to(self, target_position: tuple[float, float, float], yaw: float = 0.0) -> bool: ...

    def open_gripper(self) -> bool: ...

    def close_gripper(self) -> bool: ...

    def attempt_grasp(self, object_name: str, approach_offset: float = 0.04) -> bool: ...

    def lift_object(self, height: float) -> bool: ...

    def place_held_object(self, target_position: tuple[float, float, float]) -> bool: ...

    def resolve_zone_center(self, zone_name: str) -> tuple[float, float, float]: ...

    def resolve_object_position(self, object_name: str) -> tuple[float, float, float]: ...

    def resolve_stack_position(self, object_name: str) -> tuple[float, float, float]: ...

    def close(self) -> None: ...


class Skill(Protocol):
    name: str

    def check_preconditions(self, world: WorldState, step: SkillStep) -> SkillResult: ...

    def execute(self, adapter: SimulationAdapter, world: WorldState, step: SkillStep) -> SkillResult: ...


class Planner(Protocol):
    def plan(self, task: TaskSpec, world: WorldState) -> list[SkillStep]: ...


class PerceptionModule(Protocol):
    mode: str

    def build_world(self, adapter: SimulationAdapter, task: TaskSpec) -> tuple[WorldState, PerceptionReport]: ...


class CollectionAdapter(SimulationAdapter, Protocol):
    def capture_observation(self) -> SensorObservation: ...

    def get_oracle_world_state(self) -> WorldState: ...

    def navigate_to_waypoint(self, waypoint_name: str) -> bool: ...

    def pick_object(self, object_name: str, policy_mode: str = "scripted") -> bool: ...

    def deliver_held_object(self, zone_name: str) -> bool: ...
