"""Blender-side generator for the redistributable browser construction rover."""

from __future__ import annotations

import argparse
import math
import sys
from pathlib import Path

import bpy


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args(sys.argv[sys.argv.index("--") + 1 :])
    args.output.parent.mkdir(parents=True, exist_ok=True)
    _reset_scene()
    graphite = _material("recycled_graphite", (0.075, 0.095, 0.09, 1))
    orange = _material("safety_orange", (0.95, 0.20, 0.055, 1), metallic=0.12)
    steel = _material("brushed_steel", (0.33, 0.38, 0.37, 1), metallic=0.72)
    rubber = _material("wheel_rubber", (0.018, 0.023, 0.022, 1), roughness=0.9)
    glass = _material("sensor_glass", (0.03, 0.32, 0.35, 1), metallic=0.25)
    light = _material("status_light", (0.12, 0.8, 0.5, 1), emission=2.0)

    root = bpy.data.objects.new("construction_robot", None)
    bpy.context.collection.objects.link(root)
    _cube(root, "lower_chassis", (1.05, 0.68, 0.18), (0, 0, 0.31), graphite, bevel=0.08)
    _cube(root, "upper_chassis", (0.76, 0.56, 0.24), (0.03, 0, 0.50), orange, bevel=0.08)
    _cube(root, "front_bumper", (0.14, 0.62, 0.13), (0.56, 0, 0.28), steel, bevel=0.04)

    for x in (-0.38, 0.38):
        for y in (-0.41, 0.41):
            _cylinder(
                root,
                f"wheel_{'front' if x > 0 else 'rear'}_{'left' if y > 0 else 'right'}",
                radius=0.19,
                depth=0.14,
                location=(x, y, 0.22),
                rotation=(math.pi / 2, 0, 0),
                material=rubber,
                vertices=24,
            )
            _cylinder(
                root,
                "wheel_hub",
                radius=0.085,
                depth=0.145,
                location=(x, y, 0.22),
                rotation=(math.pi / 2, 0, 0),
                material=steel,
                vertices=20,
            )

    _cylinder(root, "arm_base", 0.18, 0.16, (0.02, 0, 0.69), (0, 0, 0), steel)
    _cube(root, "arm_mast", (0.14, 0.16, 0.62), (-0.02, 0, 0.96), orange, bevel=0.035)
    _cube(
        root,
        "lift_boom",
        (0.62, 0.12, 0.12),
        (0.22, 0, 1.21),
        steel,
        rotation=(0, math.radians(-18), 0),
        bevel=0.035,
    )
    _cube(root, "payload_fork", (0.22, 0.52, 0.06), (0.55, 0, 1.03), orange, bevel=0.025)
    _cube(root, "fork_left", (0.38, 0.055, 0.045), (0.69, 0.2, 1.03), steel, bevel=0.015)
    _cube(root, "fork_right", (0.38, 0.055, 0.045), (0.69, -0.2, 1.03), steel, bevel=0.015)

    _cylinder(root, "sensor_mast", 0.035, 0.32, (-0.24, 0, 0.91), (0, 0, 0), steel)
    _cylinder(root, "lidar", 0.12, 0.10, (-0.24, 0, 1.10), (0, 0, 0), glass, vertices=32)
    _cylinder(root, "beacon", 0.055, 0.06, (-0.24, 0, 1.19), (0, 0, 0), light, vertices=24)
    _cube(root, "camera_bar", (0.08, 0.34, 0.07), (0.48, 0, 0.58), graphite, bevel=0.025)
    for y in (-0.105, 0.105):
        _cylinder(root, "depth_camera", 0.035, 0.025, (0.525, y, 0.58), (0, math.pi / 2, 0), glass, vertices=20)

    root["asset_license"] = "Apache-2.0"
    root["asset_origin"] = "procedurally generated by Embodied Skill Composer"
    root["intended_controller"] = "task-level construction coordination"
    bpy.ops.export_scene.gltf(
        filepath=str(args.output),
        export_format="GLB",
        export_yup=True,
        export_apply=True,
    )


def _reset_scene() -> None:
    bpy.ops.object.select_all(action="SELECT")
    bpy.ops.object.delete(use_global=False)
    bpy.context.scene.unit_settings.system = "METRIC"


def _material(
    name: str,
    color: tuple[float, float, float, float],
    *,
    metallic: float = 0,
    roughness: float = 0.48,
    emission: float = 0,
):
    material = bpy.data.materials.new(name)
    material.diffuse_color = color
    material.use_nodes = True
    shader = material.node_tree.nodes.get("Principled BSDF")
    shader.inputs["Base Color"].default_value = color
    shader.inputs["Metallic"].default_value = metallic
    shader.inputs["Roughness"].default_value = roughness
    if emission:
        shader.inputs["Emission Color"].default_value = color
        shader.inputs["Emission Strength"].default_value = emission
    return material


def _cube(
    root,
    name: str,
    dimensions: tuple[float, float, float],
    location: tuple[float, float, float],
    material,
    *,
    rotation: tuple[float, float, float] = (0, 0, 0),
    bevel: float = 0.02,
) -> None:
    bpy.ops.mesh.primitive_cube_add(size=1, location=location, rotation=rotation)
    obj = bpy.context.object
    obj.name = name
    obj.dimensions = dimensions
    obj.data.materials.append(material)
    obj.parent = root
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    modifier = obj.modifiers.new("edge_softening", "BEVEL")
    modifier.width = bevel
    modifier.segments = 2


def _cylinder(
    root,
    name: str,
    radius: float,
    depth: float,
    location: tuple[float, float, float],
    rotation: tuple[float, float, float],
    material,
    *,
    vertices: int = 32,
) -> None:
    bpy.ops.mesh.primitive_cylinder_add(
        vertices=vertices,
        radius=radius,
        depth=depth,
        location=location,
        rotation=rotation,
    )
    obj = bpy.context.object
    obj.name = name
    obj.data.materials.append(material)
    obj.parent = root
    bevel = obj.modifiers.new("edge_softening", "BEVEL")
    bevel.width = 0.012
    bevel.segments = 2


if __name__ == "__main__":
    main()
